language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.7
install:
  - pip install -q Django==$DJANGO_VERSION django-model-utils
  - pip install coverage
  - pip install flake8
before_script:
  - flake8 --ignore=E501 django_permanent
script:
  - python setup.py test
  - coverage run runtests.py django_permanent
after_success:
 - pip install coveralls
 - coveralls
