language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8c1
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO_VERSION=1.7.7
   - python: "2.6"
     env: DJANGO_VERSION=1.8
install: pip install -q Django==$DJANGO_VERSION djangorestframework
script: python setup.py test
