language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
install: pip install -q Django==$DJANGO_VERSION djangorestframework
script: python setup.py test
