language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"

install:
  - pip install -q --upgrade pip
  - pip install -q $DJANGO
  - pip install -q coverage
  - pip install -q flake8

before_script:
  - flake8 --ignore=E501 django_permanent

script:
  - coverage run setup.py test

after_success:
 - pip install coveralls
 - coveralls
