language: python
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.7"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.8"
      env: DJANGO="Django>=1.7,<1.8"
    - python: "3.6"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.7"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.8"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.7"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.8"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.6"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.7"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.8"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.8"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.8"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="Django>=2.2,<3.0"
    - python: "3.4"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1"

install:
  - pip install -q --upgrade pip
  - pip install -q $DJANGO
  - pip install -q coverage
  - pip install -q flake8

before_script:
  - flake8 --ignore=E501 django_permanent

script:
  - coverage run setup.py test

after_success:
  - pip install coveralls
  - coveralls
